### ISSUE TITLE
pkg_add_description

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#1]
pkg_add_description creates invalid description file, needs author and maintainer to build

```{r}
y <- "some full path"
pkg_create_cwb_dirs(pkg = y)
pkg_add_description(pkg = y, package = "austroparl", description = "Plenary Protocols for Austria 1996 to 2018")
pkg_add_corpus(
    pkg = y, corpus = "UNGA",
    registry = "some other full path
)
pkg_add_gitattributes_file(pkg = y)
pkg_add_configure_scripts(pkg = y)
pkg_add_creativecommons_license(pkg = y)
```

**Comment by ablaette** [comment]
Good point. To prepare the initial CRAN release of cwbtools, I have removed the default value for the argument `author`(it was ""), and added a check (`missing(author)`) to the `pkg_add_description()` function. This ensures that an author is stated. In the example, I use "cwbtools" for the argument `author`.

I think the next step could/should be to rely on the package "desc" ([newly at CRAN](https://CRAN.R-project.org/package=desc)) which offers a specialised functionality to generate and manipulate DESCRIPTION files.

This is why I would like to keep this issue open, as a reminder.

**Comment by ablaette** [comment]
Functionality to download corpora from repositories has become robust and I do not consider wrapping corpora into packages as good practice any more. The `pkg_add_description()` function is declared deprecated now. Other functions for wrapping corpora into packages will follow. I started to use the lifecycle package to let user know that functions are deprecated.
