### ISSUE TITLE
Feature Request | Add corpus properties in registry file during corpus creation

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#13]
In tandem with [this issue](https://github.com/PolMine/polmineR/issues/72) in the `polmineR` package, it would be useful to add corpus properties such as build date and corpus version during the creating of the corpus instead of editing the registry file later on.

**Comment by ablaette** [comment]
I am still hesitant whether to implement this. When building GermaParl, we use this chunk to set properties:

```r
registry_file_parse(corpus = corpus_id, registry_dir = regdir) %>%
  registry_set_property("charset", "utf8") %>%
  registry_set_property("language", "de") %>%
  registry_set_property("version", params[["version"]]) %>%
  registry_set_property("build_date", as.character(Sys.Date())) %>%
  registry_set_property("type", "plpr") %>%
  registry_set_info(fs::path(data_dir, "info.md")) %>%
  registry_file_write()
``` 
The code is somewhat verbose, but not that bad. I would not include a new argument `properties` in the more basic functions `p_attribute_encode()`, but the new `encode()` method would be a plausible candidate.
