### ISSUE TITLE
as_bibentry() from Zenodo | doi shows link to unparsed record info instead of real doi

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#20]
In the return value of `as_bibentry()` the field "doi" doesn't contain the actual doi but the link to the zenodo record itself (in which a lot of metadata, among others the doi, are stored). I think that this can be remedied easily. In the line here:

https://github.com/PolMine/cwbtools/blob/f64db4394c83c295d3d2276131af40ffdbd2ab3d/R/zenodo.R#L67

Instead of "self", "doi" does contain the doi of the current version.

**Comment by ablaette** [comment]
Good point, thanks a lot for your scrutiny. I modified the line accordingly:

```r
doi_http <- x[["links"]][["doi"]]
```
