### ISSUE TITLE
Import tools::R_user_dir() or rappdirs::user_data_dir() to improve assumed location of CWB data directory

### ISSUE THREAD

**Issue by PolMine** [PolMine/cwbtools#22]
A discussion on the r-package-devel mailing list deals with the question where jar files, binary data etc should be stored (see [this thread](https://stat.ethz.ch/pipermail/r-package-devel/2020q3/005733.html)). The responses refer to `tools::R_user_dir()` and to `rappdirs::user_data_dir()` to determine a user's data directory. It might be worthwhile to consider using either of these functions to make suggestions for the CWB data directory more  robust accross platforms.

**Comment by ablaette** [comment]
The output of `tools::R_user_dir(package = "cwbtools"`is "/Users/andreasblaette/Library/Application Support/org.R-project.R/R/cwbtools"
The output of `rappdirs::user_data_dir()`is "/Users/andreasblaette/Library/Application Support"

The functions do not yield directories where most users would put there files - so I would not pursue this path.
