### ISSUE TITLE
Error message when the installation of an already existing corpus is refused

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#30]
If you try to install the same version of an already installed corpus, the installation dialogue will tell you 

> Local CORPUS version and the version of CORPUS to be downloaded are identical (CORPUS VERSION). If you proceed, the local corpus will be replaced by a fresh download.
Are you sure you want to delete registry and data files for corpus 'CORPUS'? 
1: Yes
2: No

This is nice but if you select "2: No", there is an error message which indicates trouble although everything worked as expected:

> Selection: 2
Error in corpus_remove(corpus = toupper(corpus), registry_dir = cwb_dirs[["registry_dir"]],  : 
  Aborting

It might be worth considering to provide a more reassuring reaction?

**Comment by ablaette** [comment]
This is identical with issue #25: https://github.com/PolMine/cwbtools/issues/25
And it should not be difficult to solve.
