### ISSUE TITLE
Missing s-attributes in vignette's "Scenario 2: Tidytext to CWB"

### ISSUE THREAD

**Issue by dschuele** [PolMine/cwbtools#49]
Following [Scenario 2: Tidytext to CWB from the cwbtools vignette](https://cran.r-project.org/web/packages/cwbtools/vignettes/vignette.html) creates a CWB corpus but without s-attributes.

**Comment by ablaette** [comment]
I think this is related to https://github.com/PolMine/cwbtools/issues/57#issue-2112902013: s-attributes were not reliably available after corpus encoding. This is ensured now by reloading the corpus after encoding/indexing/compression. As a safeguard, this is covered by a unit test now.
