### ISSUE TITLE
s_attribute.R on dev branch | crash on line 142 if delete TRUE and registry = registry_dir is included

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#5]
if delete TRUE, then this line crashes the entire R session

 ```{r}
if (delete) cl_delete_corpus(corpus = toupper(corpus), registry = registry_dir)
```

However changing the line to:

```{r}
  if (delete) cl_delete_corpus(corpus = toupper(corpus))
```

works.

**Comment by ablaette** [comment]
The `cl_delete_corpus()` is dangerous ... But I am not sure whether the cause is the statement of the registry directory.

This are tests I ran to provoke a crash.

```r
library(polmineR)

RcppCWB::cl_delete_corpus("REUTERS")
RcppCWB::cl_delete_corpus("GERMAPARLMINI")

RcppCWB::cqp_initialize(registry())

RcppCWB::cl_delete_corpus("GERMAPARLMINI")
RcppCWB::cl_delete_corpus("REUTERS")

RcppCWB::cl_delete_corpus("GERMAPARLMINI") # this will crash the session
```

At the end of the day, this is not a cwbtools issue, but should be solved in a new version of RcppCWB.

**Comment by ablaette** [comment]
Does not occur any more, as RcppCWB has evolved.
