### ISSUE TITLE
`corpus_install()` does not find file to download on Zenodo

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#51]
Using `cwbtools v0.3.8` and GermaParl v2 as an example, the suggested download method `corpus_install()` with a doi does not work. When resolving the DOI, there is one error stating that "no Zenodo record [was] found for DOI" as well as a warning message stating that 

> Warning message:
In zenodo_get_tarballurl(url = doi) :
  Website does not reference files to download.

The warning message seems to indicate where the error occurs. Apparently, the Zenodo webpage has changed and the xpath which is supposed to point to the tar.gz file is not returning anything:

https://github.com/PolMine/cwbtools/blob/b14c451b8ef0b6ef39a845435244a50ad6371249/R/zenodo.R#L107

**Comment by ChristophLeonhardt** [comment]
It might be possible to use the `zen4R` package again (see #42).

**Comment by ablaette** [comment]
Using zen4R again.
