### ISSUE TITLE
Vignette | Ambiguous Wording and Code

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#55]
I noticed two instances in which the vignette is ambiguous, both in scenario 1:

* there is a character vector containing the names of structural attributes, but when the corpus is encoded, the parameter `s_attributes` is set to `character()` instead
    * Note: in this scenario, it is also likely that the encoding of the structural attribute "id" will fail as the column in the metadata object contains integers instead of characters
* when encoded, the compression argument is set to FALSE, but the text assumes that the argument is set to TRUE

**Comment by ablaette** [comment]
Perfectly valid - I have changed the vignette accordingly (using s_attributes, compress = TRUE).
