### ISSUE TITLE
add gzip to corpus_as_tarball()

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/cwbtools#7]
Adding compression = gzip to tar()-function should enable gzip compression

`
tar(tarfile = tarfile, compression = "gzip")
`

**Comment by ablaette** [comment]
I have added this suggestion to the `corpus_as_tarball()` function, and have added you as a contributor to the cwbtools package.

**Comment by ablaette** [comment]
This has been resolved a while ago, so I close the issue.
