### ISSUE TITLE
cwbtools currently not installable via install.packages/cran

### ISSUE THREAD

**Issue by bandoose** [PolMine/cwbtools#73]
Error message:
> install.packages("cwbtools")
Warning in install.packages :
  package ‘cwbtools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

On cran it reads that the package was removed on 2024-04-20: https://cran.r-project.org/web/packages/cwbtools/index.html

**Comment by ablaette** [comment]
Thanks a lot for this alert! We did not manage to fix an issue reported by the CRAN team in time, see https://github.com/PolMine/cwbtools/issues/74.

cwbtools v0.4.2 is at CRAN again: https://cran.r-project.org/web/packages/cwbtools/index.html

As I write this, Windows binaries are not yet available, but this is a matter of 1-2 days. 

Of course, we will avoid another "downtime" of cwbtools at CRAN. You could also do this:

```r
devtools::install_github("PolMine/cwbtools") # install release version
devtools::install_github("PolMine/cwbtools", ref = "dev") # install development version
```
